# Arjun Ramaswami

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test

build-all:
  stage: build
  script:
    - rm -rf build
    - mkdir -p build && cd build
    - cmake ..
    - make
    - chmod +x bin/host
    - make diagonal_bitrev_emu
  artifacts:
    paths:
      - build/bin/host
      - build/bin/emu_64_diagonal_bitrev/diagonal_bitrev.aocx

test-all:
  stage: test
  script:
    - cd build/bin/
    - CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA=1 ./host -n 64 -b 1 -p emu_64_diagonal_bitrev/diagonal_bitrev.aocx
  dependencies:
    - build-all
